# Generated by Django 5.2.17 on 2026-09-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, unique=True, verbose_name='Материал')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запасы на складе')),
                ('unit', models.CharField(default='куб.м', max_length=50, verbose_name='Ед. изм.')),
                ('in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В пути (скоро поступит)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTransferAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontractor_name', models.CharField(max_length=255, verbose_name='Субподрядная организация')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Этаж / Уровень')),
                ('axes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Привязка по осям')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер помещения / Позиция')),
                ('description', models.TextField(verbose_name='Описание фронта работ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата составления')),
                ('chief_approved', models.BooleanField(default=False, verbose_name='Виза Начальника Участка')),
                ('chief_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время согласования')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.constructionobject', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialM15Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование материала')),
                ('unit', models.CharField(default='куб.м', max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Переданный объем')),
                ('sender_name', models.CharField(max_length=150, verbose_name='Отпустил (Прораб)')),
                ('receiver_name', models.CharField(max_length=150, verbose_name='Получил (Субподряд)')),
                ('is_signed_by_chief', models.BooleanField(default=False, verbose_name='Утверждено Начучастка')),
                ('passport_required', models.BooleanField(default=False, verbose_name='Запрос паспорта изделия (ПТО)')),
                ('passport_file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на скачанный PDF сертификат')),
                ('passport_status', models.CharField(default='Не затребован', max_length=100, verbose_name='Статус проверки ГОСТ')),
                ('act_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_control.spacetransferact', verbose_name='Привязка к Акту')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Материал')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Требуемый объем')),
                ('target_date', models.DateField(verbose_name='Дата поставки (на день наперед)')),
                ('status', models.CharField(choices=[('pending', 'На согласовании (3 дня)'), ('approved', 'Утверждено / Тайм-слот выдан'), ('deficit', 'Отсутствует / Срочный дозаказ'), ('discrepancy', 'Акт несоответствия (Пересортица)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.constructionobject')),
            ],
        ),
        migrations.CreateModel(
            name='EzhikRouteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_map_data', models.TextField(verbose_name='Оптимальный маршрут (Тула - Объект)')),
                ('assigned_driver', models.CharField(max_length=150, verbose_name='Водитель снабжения')),
                ('is_dispatched', models.BooleanField(default=False, verbose_name='Задание направлено')),
                ('request_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage_control.supplyrequest')),
            ],
        ),
    ]
