# Generated by Django 5.2.17 on 2026-09-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvatarEzhik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active_2026', max_length=100)),
                ('profit_alerts', models.CharField(default='Lava Pay Active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CascadeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_detail', models.TextField()),
                ('target_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='РосКапиталСтрой', max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, default=15000000.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(default='Мирослава Косарева', max_length=255)),
                ('record_type', models.CharField(default='Детское слово', max_length=100)),
                ('text_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(default='news', max_length=50)),
                ('title', models.CharField(default='', max_length=255)),
                ('comment_text', models.TextField(default='')),
                ('is_approved_by_ezhik', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('country', models.CharField(default='Российская Федерация', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_intent', models.TextField(default='Scan')),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('reviewer_role', models.CharField(default='РУКОВОДИТЕЛЬ ПРОЕКТА', max_length=50)),
                ('ezhik_verdict', models.TextField(default='Ждем проверки.')),
            ],
        ),
        migrations.CreateModel(
            name='PunchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('video_file', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BloggerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_name', models.CharField(default='max_kosarev', max_length=100)),
                ('daily_limit', models.IntegerField(default=12)),
                ('accumulated_income', models.DecimalField(decimal_places=2, default=15000000.0, max_digits=15)),
                ('accessible_capsules', models.ManyToManyField(blank=True, to='storage_control.videocapsule')),
            ],
        ),
    ]
