# Generated by Django 6.0.5 on 2026-05-24 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule_id', models.CharField(max_length=255, unique=True, verbose_name='ID Капсулы / Маяк')),
                ('category', models.CharField(choices=[('FAMILY', 'Золотое Тепло (Семья)'), ('SCIENCE', 'Глобальный Маяк (Наука и Религия)'), ('GOST', 'Цифровая Каска (ГОСТ / Стройка)')], default='FAMILY', max_length=20, verbose_name='Контур/Категория')),
                ('teaser_video_path', models.CharField(max_length=500, verbose_name='Путь к Тизеру (Первый показ)')),
                ('unlock_date', models.DateTimeField(verbose_name='Дата автоматического открытия')),
                ('unlock_age', models.IntegerField(blank=True, null=True, verbose_name='Возраст получателя для открытия')),
                ('receiver_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('face_vector_bin', models.BinaryField(blank=True, null=True, verbose_name='Биометрический вектор (Ключ)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный контур (Разрешен экспорт в TikTok/YouTube)')),
                ('is_approved_by_ezhik', models.BooleanField(default=False, verbose_name='Проверено ИИ-Модерацией Ёжика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уговор (Протокол)',
                'verbose_name_plural': 'Уговоры (Протоколы)',
            },
        ),
        migrations.CreateModel(
            name='AvatarEzhik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ёжик', max_length=255, verbose_name='Имя Аватара')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Общий доход (Рубли/USD)')),
                ('analytics_report', models.TextField(blank=True, null=True, verbose_name='Аналитический отчет для Мирославы')),
                ('development_proposals', models.TextField(blank=True, null=True, verbose_name='Предложения по расширению ствола бизнеса')),
                ('is_learning', models.BooleanField(default=True, verbose_name='Статус обучения ИИ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аватар Ёжик',
                'verbose_name_plural': 'Аватары Ёжики',
            },
        ),
        migrations.CreateModel(
            name='BloggerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('photo_video_count', models.IntegerField(default=0)),
                ('last_upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(choices=[('family', 'Золотое Тепло (Семья)'), ('construction', 'Цифровая Каска (Стройка)'), ('science', 'Глобальный Маяк (Наука и Религия)')], default='family', max_length=50, verbose_name='Папка Блога')),
                ('author_name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Очищенный текст')),
                ('source_platform', models.CharField(default='local', max_length=100, verbose_name='Источник (Local/Google/Yandex)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP для жесткого бана спамеров')),
                ('is_approved_by_ezhik', models.BooleanField(default=False, verbose_name='Одобрено функцией is_approved_by_ezhik')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Интерактивный комментарий',
                'verbose_name_plural': 'Интерактивные комментарии',
            },
        ),
        migrations.CreateModel(
            name='PunchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_block', models.CharField(default='Корпус 1', max_length=100, verbose_name='Корпус/Сектор')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('room', models.CharField(max_length=50, verbose_name='Помещение/Комната')),
                ('axis', models.CharField(max_length=100, verbose_name='Строительная ось')),
                ('description', models.TextField(verbose_name='Описание несоответствия СНиП')),
                ('wood_humidity', models.FloatField(blank=True, null=True, verbose_name='Влажность древесины (%) по ГОСТ 475')),
                ('assigned_to', models.CharField(max_length=255, verbose_name='Ответственный подрядчик/Бригада')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Устранено')),
                ('approved_by_author', models.BooleanField(default=False, verbose_name='Утверждено Авторским надзором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации')),
            ],
            options={
                'verbose_name': 'Строительный дефект',
                'verbose_name_plural': 'Панч-лист: Реестр дефектов',
                'indexes': [models.Index(fields=['building_block', 'floor', 'room'], name='storage_con_buildin_472c8a_idx'), models.Index(fields=['is_closed'], name='storage_con_is_clos_b9fef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoCapsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу видео на диске')),
                ('is_processed_by_director', models.BooleanField(default=False, verbose_name='Обработано Нейро-Режиссером (FFmpeg)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='storage_control.agreement', verbose_name='Уговор')),
            ],
            options={
                'verbose_name': 'Видео Капсула',
                'verbose_name_plural': 'Видео Капсулы',
            },
        ),
    ]
