# Generated by Django 5.2.17 on 2026-09-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_title', models.CharField(max_length=200, verbose_name='Заголовок Статьи / Монолога / Лога')),
                ('log_content', models.TextField(verbose_name='Тело Монолога / Содержимое Директивы')),
                ('media_file_path', models.CharField(blank=True, help_text='Обработка через imageio/moviepy/pillow', max_length=255, null=True, verbose_name='Путь к загруженному Медиа (Фото/Видео/Аватарка)')),
                ('captured_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка Вечности')),
            ],
            options={
                'verbose_name': 'Директива Архива / Монолог',
                'verbose_name_plural': '💾 4. Директивы Архива и Монологи',
            },
        ),
        migrations.CreateModel(
            name='MezaninWebsiteBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Название Сайта / Проекта')),
                ('site_domain', models.CharField(help_text='Напр: blog.miroha.ru', max_length=100, verbose_name='Технический Домен / Туннель')),
                ('architecture_type', models.CharField(choices=[('BLOG', 'Блог ИТР-Монологов'), ('VCARD', 'Сайт-Визитка СРО'), ('CHATBOT', 'Интерфейс Чат-Бота')], default='BLOG', max_length=20, verbose_name='Тип Конструктора Мезонина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Запустить в полный ОЗУ-эфир Nginx?')),
            ],
            options={
                'verbose_name': 'Сайт Конструктора Мезонина',
                'verbose_name_plural': '💻 3. Конструктор Сайтов и Блогов',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='Напр: MIRO-MASTER-BOSS-2026', max_length=100, unique=True, verbose_name='Ключ Лицензии ПО')),
                ('license_type', models.CharField(help_text='Линейная ИТР, Полный Мезонин, Благотворительная', max_length=100, verbose_name='Пакет / Тип Лицензии')),
                ('status', models.CharField(choices=[('ACTIVE', 'АКТИВНА // Secured'), ('EXPIRED', 'ИСТЕКЛА // Blocked')], default='ACTIVE', max_length=20, verbose_name='Статус Лицензии в Postgres')),
                ('expires_at', models.DateField(verbose_name='Срок действия Лицензии')),
            ],
            options={
                'verbose_name': 'Коммерческая Лицензия ПО',
                'verbose_name_plural': '📜 2. Контур Лицензирования ПО',
            },
        ),
        migrations.CreateModel(
            name='UserMaskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Напр: CID-PRO-MIHALYCH', max_length=50, unique=True, verbose_name='ИТР Код Client ID')),
                ('active_role', models.CharField(help_text='Администратор, ПТО, Разнорабочий, Отец для вечности и т.д.', max_length=100, verbose_name='Активная Маска / Роль')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона для связи')),
                ('google_totp_secret', models.CharField(blank=True, max_length=64, null=True, verbose_name='Криптографический КЛЮЧ-ТОННЕЛЬ (Base32)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата фиксации в вечности')),
            ],
            options={
                'verbose_name': 'Маска Максима / Профиль Пользователя',
                'verbose_name_plural': '👥 1. Матрица Масок и Профилей',
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='spacetransferact',
            name='construction_object',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='construction_object',
        ),
        migrations.DeleteModel(
            name='EzhikUserCabinet',
        ),
        migrations.DeleteModel(
            name='EzhikVideoVault',
        ),
        migrations.DeleteModel(
            name='ItrProrabTest',
        ),
        migrations.DeleteModel(
            name='LiveStreamMessage',
        ),
        migrations.RemoveField(
            model_name='materialm15invoice',
            name='act_link',
        ),
        migrations.DeleteModel(
            name='ServerBalance',
        ),
        migrations.DeleteModel(
            name='WarehouseStock',
        ),
        migrations.AddField(
            model_name='archivaldirective',
            name='associated_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.mezaninwebsitebuilder', verbose_name='Связанный Проект'),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.usermaskprofile', verbose_name='Привязка к Профилю'),
        ),
        migrations.AddField(
            model_name='mezaninwebsitebuilder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.usermaskprofile', verbose_name='Создатель / Администратор'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='PartnerProduct',
        ),
        migrations.DeleteModel(
            name='ConstructionObject',
        ),
        migrations.DeleteModel(
            name='SupplyRequest',
        ),
        migrations.DeleteModel(
            name='MaterialM15Invoice',
        ),
        migrations.DeleteModel(
            name='SpaceTransferAct',
        ),
    ]
