# Generated by Django 5.2.17 on 2026-09-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItrProrabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prorab_name', models.CharField(max_length=150, verbose_name='ФИО Прораба (Линия)')),
                ('work_stage', models.CharField(default='Заливка плиты перекрытия', max_length=255, verbose_name='Этап / Вид строительных работ')),
                ('photo_1_axis', models.CharField(default='/static/img/axis.png', max_length=500, verbose_name='Фото 1: Оси')),
                ('photo_2_reinforcement', models.CharField(default='/static/img/arm.png', max_length=500, verbose_name='Фото 2: Арматура')),
                ('photo_3_shuttering', models.CharField(default='/static/img/shutter.png', max_length=500, verbose_name='Фото 3: Опалубка')),
                ('photo_4_ready_work', models.CharField(default='/static/img/ready.png', max_length=500, verbose_name='Фото 4: Готовый вид')),
                ('delivery_delay_detected', models.BooleanField(default=False, verbose_name='Нарушение сроков доставки')),
                ('visible_defects_notes', models.TextField(blank=True, null=True, verbose_name='Дефекты видимых работ')),
                ('aosr_generated', models.BooleanField(default=True, verbose_name='АОСР сгенерирован')),
                ('defect_sheet_issued', models.BooleanField(default=False, verbose_name='Дефектная ведомость выписана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('message_text', models.TextField(verbose_name='Сообщение')),
                ('ezhik_reply', models.TextField(blank=True, null=True, verbose_name='Ответ Ёжика')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('partner_name', models.CharField(max_length=150, verbose_name='Поставщик / Партнер')),
                ('image_url', models.CharField(default='/static/img/default_prod.png', max_length=500, verbose_name='Ссылка на картинку/гифку товара')),
                ('sales_count', models.IntegerField(default=142, verbose_name='Счетчик общих покупок')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='target_date',
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='city',
            field=models.CharField(default='Тула', max_length=100, verbose_name='Город / Локация матрицы'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна присутствия'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='currency',
            field=models.CharField(default='RUB', max_length=10, verbose_name='Валюта расчетов'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='object_capital',
            field=models.DecimalField(decimal_places=2, default=15000000.0, max_digits=15, verbose_name='Капитал объекта / Бюджет'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название ИТ-Объекта / Холдинга'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='in_transit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='В пути'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.partnerproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='EzhikRouteCard',
        ),
    ]
