# Generated by Django 5.2.17 on 2026-09-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0002_alter_bloggerusage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('director', 'Директор Холдинга (Глобальный контроль)'), ('manager', 'Руководитель проекта (Управление объектом)'), ('prorab', 'Прораб на участке (Исполнение в зоне)')], max_length=20, verbose_name='Для какой роли задача')),
                ('task_title', models.CharField(max_length=250, verbose_name='Суть задачи / Наряд')),
                ('task_detail', models.TextField(verbose_name='Инструкция и ведомость СНиП')),
                ('ezhik_ai_analysis', models.TextField(blank=True, null=True, verbose_name='Анализ рисков и предложение Ёжика')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='Название Холдинга/Компании')),
                ('license_status', models.BooleanField(default=True, verbose_name='Лицензия Активна')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Глобальный Бюджет Холдинга')),
            ],
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='avatarezhik',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bloggerusage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interactivecomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='punchlistitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videocapsule',
            options={},
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='capsule_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='face_vector_bin',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='is_approved_by_ezhik',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='receiver_email',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='seo_slug',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='teaser_video_path',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='unlock_age',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='unlock_date',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='is_learning',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='name',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bloggerusage',
            name='last_upload_date',
        ),
        migrations.RemoveField(
            model_name='bloggerusage',
            name='photo_video_count',
        ),
        migrations.RemoveField(
            model_name='bloggerusage',
            name='username',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='blog_type',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='approved_by_author',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='building_block',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='geo_lon',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='room',
        ),
        migrations.RemoveField(
            model_name='videocapsule',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='videocapsule',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='videocapsule',
            name='is_processed_by_director',
        ),
        migrations.RemoveField(
            model_name='videocapsule',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(default='Вековое Соглашение Холдинга FAMILYMIRO', max_length=250, verbose_name='Название соглашения/оферты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarezhik',
            name='ai_recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации Ёжика Хозяйке'),
        ),
        migrations.AddField(
            model_name='avatarezhik',
            name='opencv_logs',
            field=models.TextField(blank=True, null=True, verbose_name='Логи Нейро-Радара OpenCV'),
        ),
        migrations.AddField(
            model_name='avatarezhik',
            name='profit_alerts',
            field=models.TextField(blank=True, null=True, verbose_name="Уведомления о прибыли Lava Pay ('лаве')"),
        ),
        migrations.AddField(
            model_name='avatarezhik',
            name='status',
            field=models.CharField(default='Active_2026', max_length=100, verbose_name='Текущий Статус ИИ'),
        ),
        migrations.AddField(
            model_name='bloggerusage',
            name='accumulated_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Заработанное 'лаве' (%)"),
        ),
        migrations.AddField(
            model_name='bloggerusage',
            name='blogger_name',
            field=models.CharField(default='Miroslava_Kosareva', max_length=150, verbose_name='Имя Блогера / ИТР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloggerusage',
            name='daily_limit',
            field=models.IntegerField(default=12, verbose_name='Лимит медиа в день'),
        ),
        migrations.AddField(
            model_name='interactivecomment',
            name='category_type',
            field=models.CharField(choices=[('news', 'Новость'), ('snip', 'СНиП Ссылка'), ('poetry', 'Стихи')], default='news', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='interactivecomment',
            name='comment_text',
            field=models.TextField(default='Сила Ёжика охраняет контур Открытого Неба РФ.', verbose_name='Очищенный текст материала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivecomment',
            name='title',
            field=models.CharField(default='Находка Хранителя', max_length=250, verbose_name='Заголовок находки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='defect_description',
            field=models.TextField(default='Первичный аудит контура снабжения. Дефектов по СНиП не обнаружено.', verbose_name='Дефект или объём заливки бетона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Верифицировано OpenCV (ГОСТ 475-2016)'),
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='paint_barrels',
            field=models.IntegerField(default=0, verbose_name='Закупка бочек краски (шт)'),
        ),
        migrations.AddField(
            model_name='videocapsule',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Доступно для SHOP'),
        ),
        migrations.AddField(
            model_name='videocapsule',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеофайл OpenCV/FFmpeg'),
        ),
        migrations.AddField(
            model_name='videocapsule',
            name='video_title',
            field=models.CharField(default='Главный Эфир Капитана', max_length=200, verbose_name='Название ролика TikTok/YouTube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloggerusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='is_approved_by_ezhik',
            field=models.BooleanField(default=False, verbose_name='Одобрено в печать'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videocapsule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_control.cascadetask', verbose_name='Привязанный наряд каскада'),
        ),
        migrations.AddField(
            model_name='cascadetask',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_control.constructioncompany', verbose_name='Компания/Объект'),
        ),
    ]
