# Generated by Django 5.2.17 on 2026-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0002_itrprorabtest_livestreammessage_partnerproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_rub', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс хостинга (Реальный)')),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Уплаченный налог самозанятости')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
