# Generated by Django 5.2.17 on 2026-09-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0003_serverbalance'),
    ]

    operations = [
    ]
