# Generated by Django 5.2.17 on 2026-09-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0004_auto_20260915_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzhikUserCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ сессии / Идентификатор')),
                ('assigned_name', models.CharField(default='Странник Наследия', max_length=150, verbose_name='Имя, присвоенное Ёжиком')),
                ('moba_style_preference', models.CharField(default='cyan', max_length=100, verbose_name='Личный неоновый стиль')),
                ('ezhik_charm_level', models.IntegerField(default=100, verbose_name='Уровень Шарма Ёжика')),
                ('user_country', models.CharField(default='Россия', max_length=100, verbose_name='Локация пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
