# Generated by Django 5.2.17 on 2026-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0005_ezhikusercabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzhikVideoVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='Детская улыбка / Вечность', max_length=255, verbose_name='Название / Описание видео')),
                ('video_file_url', models.CharField(max_length=500, verbose_name='Ссылка на видеофайл')),
                ('country_origin', models.CharField(default='Россия', max_length=100, verbose_name='Страна загрузки')),
                ('eyes_detected', models.BooleanField(default=True, verbose_name='Фиксация взгляда (Глаза)')),
                ('smile_detected', models.BooleanField(default=True, verbose_name='Фиксация эмоций (Улыбка)')),
                ('hands_detected', models.BooleanField(default=True, verbose_name='Фиксация жестов (Руки)')),
                ('audio_cleaned', models.BooleanField(default=True, verbose_name='Очистка звука и речи выполнена')),
                ('is_approved_by_ezhik', models.BooleanField(default=True, verbose_name='Прошел ИИ-Сито (Мусор удален)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
