version: '3.8'

services:
  # 🌐 КОНТУР БЭКЕНДА — DJANGO НА ИЗОЛИРОВАННОМ ПОРТУ 8080
  web_django:
    image: python:3.10-slim
    container_name: familymiro_web_core
    volumes:
      - /root/app:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python manage.py check && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka_kraft:9092
    restart: always

  # 📡 БРОКЕР ОЧЕРЕДЕЙ — APACHE KAFKA В ОПТИМИЗИРОВАННОМ РЕЖИМЕ KRAFT (МИНУС RAM)
  kafka_kraft:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_kraft_broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL_CONTOUR:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka_kraft:9092,SSL_CONTOUR://89.111.155.234:9092'
      KAFKA_OFFERS_FOR_CONTROLLERS: 'CONTROLLER://kafka_kraft:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTg0NEI3Qk'
    restart: always

  # 🛡️ ВНУТРЕННИЙ ЩИТ ДЛЯ КОНТЕЙНЕРОВ НА СВОБОДНОМ ПОРТУ 9090
  nginx_shield:
    image: nginx:alpine
    container_name: nginx_secure_shield
    ports:
      - "127.0.0.1:9090:80"
    volumes:
      - /root/app/storage_control/static:/app/static:ro
    restart: always
