# Generated by Django 5.2.14 on 2026-05-26 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggerusage',
            options={'verbose_name': 'Лимит Блогера', 'verbose_name_plural': 'Лимиты Блогеров'},
        ),
        migrations.AlterModelOptions(
            name='interactivecomment',
            options={'verbose_name': 'Интерактивный комментарий', 'verbose_name_plural': 'Interactive Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='punchlistitem',
            options={'verbose_name': 'Замечание Технадзора', 'verbose_name_plural': 'Замечания Технадзора'},
        ),
        migrations.RemoveIndex(
            model_name='punchlistitem',
            name='storage_con_buildin_472c8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='punchlistitem',
            name='storage_con_is_clos_b9fef6_idx',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='analytics_report',
        ),
        migrations.RemoveField(
            model_name='avatarezhik',
            name='development_proposals',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='source_platform',
        ),
        migrations.RemoveField(
            model_name='interactivecomment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='punchlistitem',
            name='wood_humidity',
        ),
        migrations.AddField(
            model_name='agreement',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта памяти'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота памяти'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Описание Snippet'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seo_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='ЧПУ URL для Яндекса/Google'),
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта дефекта'),
        ),
        migrations.AddField(
            model_name='punchlistitem',
            name='geo_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота дефекта'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='is_learning',
            field=models.BooleanField(default=True, verbose_name='ИИ-Самообучение активно'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='name',
            field=models.CharField(default='Автономный Савелий/Ёжик', max_length=100, verbose_name='Имя Аватара'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='total_revenue',
            field=models.FloatField(default=0.0, verbose_name='Пассивный доход (руб.)'),
        ),
        migrations.AlterField(
            model_name='avatarezhik',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='bloggerusage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloggerusage',
            name='last_upload_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата крайней загрузки'),
        ),
        migrations.AlterField(
            model_name='bloggerusage',
            name='photo_video_count',
            field=models.IntegerField(default=0, verbose_name='Использовано за смену'),
        ),
        migrations.AlterField(
            model_name='bloggerusage',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Никнейм Блогера'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='author_name',
            field=models.CharField(max_length=150, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='blog_type',
            field=models.CharField(max_length=100, verbose_name='Тип блога'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interactivecomment',
            name='is_approved_by_ezhik',
            field=models.BooleanField(default=False, verbose_name='Пропущено ИИ-Щитом'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='approved_by_author',
            field=models.BooleanField(default=False, verbose_name='Согласовано Автором'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='assigned_to',
            field=models.CharField(max_length=150, verbose_name='Ответственный исполнитель'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='axis',
            field=models.CharField(max_length=100, verbose_name='Привязка к Осям'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='building_block',
            field=models.CharField(max_length=100, verbose_name='Корпус / Блок'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='description',
            field=models.TextField(verbose_name='Описание замечания'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='floor',
            field=models.CharField(max_length=50, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Замечание устранено'),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='room',
            field=models.CharField(max_length=50, verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='videocapsule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
